language: android
android:
  components:
    - build-tools-29.0.3
    - android-29
deploy:
  provider: releases
  api_key:
    secure: acO3ZSKoza29Yg6gEPEG2pYumRA4swkrkksNqmjJdVkWZ7VgiRlv2u6J/Xc8t9Zp0JfQX5EMAqgq4ZrtUOa6rOuj63+zi5Jq94R0TP6O6b2fdIpBvBGBF0/WMThvqH4ZO/kqwyvumViFWolvXvxAD/QIiAaZYTw9aqwzk9n2XdaYAZyknZnFD+mxB5iHWnfXTt3GbImAk8G0o28OfPzx/1uQvd4komud4Y5rPTXqtr5KMuFUshAU0DaNhQdqfkoaKmzUOo8vzvv8xSVeiVOQFvY6k9mpyZ8tovtO3VfHCyCm2uVEWW7SyIRmJjT/qgwaBsZUI/x+7O1suO0AWmBh7qNkKnh/sv0y+oLZPjSBQQ7WfIBOfjNrPjvOiFjV9NmRyJ5d66MW0uM30oMKSyf7EMnCXCH3N4BPGkA5gywDmLM7UnmugdzgFbxDXmYFyWnSUqXMPLFes67YM8YMJrWQe/9uYluul0HP68DvLLNlTVNU5h38qWRJnWfBEdNbFAURFW0ivTqIN0qZeEYHD3ARBG/bomnfzrXIyP9+LQ0deWXEICt8pkFA4+MWfDAqvHrZshukPmPrZ8C1Wa+SVu36HS7DEnqyE6nDlEye9/85jxf0ibitszXCA/cbxYSKVMGLxm4cWB3iTazb8cTPsXZ8A6aPAoL1MujWAWp4aQ2EEwI=
  file_glob: true
  file:
    - app/build/outputs/apk/release/*.apk
    - app/build/outputs/mapping/release/mapping.txt
  skip_cleanup: 'true'
  on:
    tags: true
